/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Datos.registro;
import model.usuario;
import model.rol;
import Controller.Sesion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josue Ambrocio
 */
public class mantenimientoUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mantenimientoUsuarios.class.getName());
    
    // Modelo de tabla
    private javax.swing.table.DefaultTableModel modeloTabla;

    /**
     * Creates new form mantenimientoUsuarios
     */
    public mantenimientoUsuarios() {
        initComponents();
        this.setTitle("Mantenimiendo de Usuarios");
        configurarTabla();

        if (Sesion.usuarioActual.getRol() != rol.ADMIN) {
            cmbRol.setEnabled(false);
        }
    }
    
    private void configurarTabla() {
    modeloTabla = new DefaultTableModel(
        new Object[]{"USUARIO", "NOMBRE", "CORREO", "ESTADO", "ROL", "PASSWORD"}, 0
    ) {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    tblUsuarios.setModel(modeloTabla);
    cargarTabla();
}

    private void cargarTabla() {
        modeloTabla.setRowCount(0);

        for (usuario u : registro.usuarios) {
            modeloTabla.addRow(new Object[]{
                u.getUsername(),
                u.getNombre(),
                u.getCorreo(),
                u.isActivo() ? "ACTIVO" : "INACTIVO",
                u.getRol(),
                u.getPassword()
            });
        }
    }
    
    private boolean validarCorreo(String correo) {

        if (!correo.contains("@")) {
            JOptionPane.showMessageDialog(this, "El correo debe contener '@'");
            return false;
        }

        if (!correo.contains(".")) {
            JOptionPane.showMessageDialog(this, "El correo debe contener dominio (.com, etc)");
            return false;
        }

        return true;
    }
    
    private void cargarDatosDesdeTabla() {
        int fila = tblUsuarios.getSelectedRow();

        if (fila >= 0) {
            txtUsuario.setText(tblUsuarios.getValueAt(fila, 0).toString());
            txtNombre.setText(tblUsuarios.getValueAt(fila, 1).toString());
            txtCorreo.setText(tblUsuarios.getValueAt(fila, 2).toString());
            txtPassword.setText(tblUsuarios.getValueAt(fila, 5).toString());

            cmbEstado.setSelectedItem(tblUsuarios.getValueAt(fila, 3).toString());
            cmbRol.setSelectedItem(tblUsuarios.getValueAt(fila, 4).toString());
        }
    }
    
    private boolean validarPassword(String pass) {

        if (pass.length() < 13) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener mínimo 13 caracteres");
            return false;
        }

        if (!pass.matches(".*[A-Z].*")) {
            JOptionPane.showMessageDialog(this, "Debe contener al menos una mayúscula");
            return false;
        }

        if (!pass.matches(".*[^a-zA-Z0-9].*")) {
            JOptionPane.showMessageDialog(this, "Debe contener al menos un símbolo especial");
            return false;
        }

        return true;
    }
 
    private void limpiarFormulario() {
        txtUsuario.setText("");
        txtNombre.setText("");
        txtCorreo.setText("");
        txtPassword.setText("");

        cmbEstado.setSelectedItem("ACTIVO");
        cmbRol.setSelectedItem("USER");

        tblUsuarios.clearSelection();
    }
 
    private boolean validarCampos() {
        if (txtUsuario.getText().trim().isEmpty() ||
            txtNombre.getText().trim().isEmpty() ||
            txtCorreo.getText().trim().isEmpty() ||
            new String(txtPassword.getPassword()).trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Todos los campos son obligatorios.",
                "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
 
    private boolean usuarioExiste(String usuario) {
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            if (modeloTabla.getValueAt(i, 0).toString().equalsIgnoreCase(usuario)) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        scrollTable = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lblLista = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnIncativar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblRol = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(45, 45, 107));

        jPanel1.setBackground(new java.awt.Color(62, 62, 112));

        lblNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(192, 192, 224));
        lblNombre.setText("Nombre Completo: ");

        lblCorreo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(192, 192, 224));
        lblCorreo.setText("Correo Electrónico:");

        lblPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(192, 192, 224));
        lblPassword.setText("Password:");

        lblEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(192, 192, 224));
        lblEstado.setText("Estado:");

        txtNombre.setPreferredSize(new java.awt.Dimension(250, 25));

        txtCorreo.setPreferredSize(new java.awt.Dimension(250, 25));

        txtPassword.setToolTipText("");
        txtPassword.setPreferredSize(new java.awt.Dimension(250, 25));

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(192, 192, 224));
        lblUsuario.setText("Usuario:");

        txtUsuario.setPreferredSize(new java.awt.Dimension(250, 25));
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        cmbEstado.setPreferredSize(new java.awt.Dimension(250, 25));
        cmbEstado.addActionListener(this::cmbEstadoActionPerformed);

        scrollTable.setPreferredSize(new java.awt.Dimension(570, 150));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USUARIO", "NOMBRE", "CORREO", "ESTADO", "ROL", "PASSWORD"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        scrollTable.setViewportView(tblUsuarios);

        lblLista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLista.setForeground(new java.awt.Color(192, 192, 224));
        lblLista.setText("Lista de Usuarios:");

        btnAgregar.setBackground(new java.awt.Color(232, 64, 90));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setOpaque(true);
        btnAgregar.setPreferredSize(new java.awt.Dimension(110, 28));
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(232, 64, 90));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorderPainted(false);
        btnModificar.setOpaque(true);
        btnModificar.setPreferredSize(new java.awt.Dimension(110, 28));
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnIncativar.setBackground(new java.awt.Color(136, 136, 136));
        btnIncativar.setForeground(new java.awt.Color(255, 255, 255));
        btnIncativar.setText("INCATIVAR");
        btnIncativar.setBorderPainted(false);
        btnIncativar.setOpaque(true);
        btnIncativar.setPreferredSize(new java.awt.Dimension(110, 28));
        btnIncativar.addActionListener(this::btnIncativarActionPerformed);

        jPanel2.setBackground(new java.awt.Color(26, 26, 74));

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("MANTENIMIENTO DE USUARIOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnVolver.setBackground(new java.awt.Color(45, 45, 107));
        btnVolver.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(192, 192, 224));
        btnVolver.setText("← Volver al Menú");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 85, 170)));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setOpaque(true);
        btnVolver.setPreferredSize(new java.awt.Dimension(140, 28));
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        lblRol.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRol.setForeground(new java.awt.Color(192, 192, 224));
        lblRol.setText("Roles: ");

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USUER", "ADMIN" }));
        cmbRol.setPreferredSize(new java.awt.Dimension(250, 25));
        cmbRol.addActionListener(this::cmbRolActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblLista, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnIncativar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(lblRol))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncativar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lblLista)
                .addGap(18, 18, 18)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String user = txtUsuario.getText().trim();
        String pass = new String(txtPassword.getPassword());
        String correo = txtCorreo.getText().trim();
        String nombre = txtNombre.getText().trim();
        String estado = cmbEstado.getSelectedItem().toString();

        if (user.isEmpty() || pass.isEmpty() || correo.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campos vacíos");
            return;
        }

        if (!validarCorreo(correo)) return;
        if (!validarPassword(pass)) return;

        if (estado.equals("INACTIVO")) {
            JOptionPane.showMessageDialog(this, "No se puede crear un usuario INACTIVO");
            return;
        }

        for (usuario u : registro.usuarios) {

                if (u.getCorreo().equalsIgnoreCase(correo)) {


                    if (u.getUsername().equalsIgnoreCase(user)) {

                        JOptionPane.showMessageDialog(this, "El usuario ya existe, se actualizarán los datos");

                        u.setNombre(nombre);
                        u.setPassword(pass);
                        u.setCorreo(correo);

                        cargarTabla();
                        limpiarFormulario();
                        return;
                    }

                    JOptionPane.showMessageDialog(this, "El correo ya está registrado en otro usuario");
                    return;
                }
            }

            for (usuario u : registro.usuarios) {
                if (u.getUsername().equalsIgnoreCase(user)) {
                    JOptionPane.showMessageDialog(this, "El usuario ya existe, usa MODIFICAR");
                    return;
                }
            }

            rol rolNuevo;

            if (Sesion.usuarioActual.getRol() == rol.ADMIN) {
                rolNuevo = cmbRol.getSelectedItem().toString().equals("ADMIN") ? rol.ADMIN : rol.USER;
            } else {
                rolNuevo = rol.USER;
            }

            registro.usuarios.add(
                new usuario(user, pass, rolNuevo, true, nombre, correo)
            );

            cargarTabla();
            limpiarFormulario();

            JOptionPane.showMessageDialog(this, "Usuario agregado correctamente");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnIncativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncativarActionPerformed
        int fila = tblUsuarios.getSelectedRow();

    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario");
        return;
    }

    if (Sesion.usuarioActual.getRol() != rol.ADMIN) {
        JOptionPane.showMessageDialog(this, "Solo ADMIN puede inactivar");
        return;
    }

    registro.usuarios.get(fila).setActivo(false);

    cargarTabla();
    limpiarFormulario();

    JOptionPane.showMessageDialog(this, "Usuario inactivado");
    }//GEN-LAST:event_btnIncativarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menuPrincipal menu = new menuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
      int fila = tblUsuarios.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario");
            return;
        }

        usuario u = registro.usuarios.get(fila);

        if (Sesion.usuarioActual.getRol() != rol.ADMIN && u.getRol() == rol.ADMIN) {
            JOptionPane.showMessageDialog(this, "No puedes modificar usuarios ADMIN");
            return;
        }

        String pass = new String(txtPassword.getPassword());
        String nombre = txtNombre.getText();
        String correo = txtCorreo.getText();

        if (!validarCorreo(correo)) return;
        if (!validarPassword(pass)) return;

        u.setPassword(pass);
        u.setNombre(nombre);
        u.setCorreo(correo);

        String estadoNuevo = cmbEstado.getSelectedItem().toString();
        String estadoActual = u.isActivo() ? "ACTIVO" : "INACTIVO";

        if (!estadoNuevo.equals(estadoActual)) {

            if (Sesion.usuarioActual.getRol() != rol.ADMIN) {
                JOptionPane.showMessageDialog(this, "Solo ADMIN puede cambiar el estado");


                cmbEstado.setSelectedItem(estadoActual);

            } else {
                u.setActivo(estadoNuevo.equals("ACTIVO"));
            }
        }

        String rolNuevo = cmbRol.getSelectedItem().toString();
        String rolActual = u.getRol().toString();

        if (!rolNuevo.equals(rolActual)) {

            if (Sesion.usuarioActual.getRol() != rol.ADMIN) {
                JOptionPane.showMessageDialog(this, "Solo ADMIN puede cambiar roles");

             
                cmbRol.setSelectedItem(rolActual);

            } else {
                u.setRol(rolNuevo.equals("ADMIN") ? rol.ADMIN : rol.USER);
            }
        }

        cargarTabla();
        limpiarFormulario();

        JOptionPane.showMessageDialog(this, "Usuario modificado correctamente");
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        cargarDatosDesdeTabla();
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mantenimientoUsuarios().setVisible(true));
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnIncativar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblLista;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
